#!/usr/bin/env python3
"""Run every language's text through every applicable classical cipher,
computing letter/word/morpheme statistics at multiple text-window sizes,
and emit per (language, cipher) CSVs suitable for downstream ML training.

See output/README.md (generated by this script) for the full column
glossary and the scope decisions behind it.
"""
import argparse
import csv
import os
import random
import statistics as pystats
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pipeline.manifest import build_manifest
from pipeline.corpus import group_usable_by_language, get_or_build_corpus, MIN_USABLE_CORPUS_CHARS
from pipeline.tokenize import tokenize_words, is_word_segmented
from pipeline.morphemes import train_bpe, segment_text
from pipeline.ciphers import CIPHERS, CIPHERS_BY_ID, PUA_START, PUA_CAPACITY, homophonic_symbol_budget
from pipeline.stats import (
    unigram_stats, bigram_stats, repeat_spacing_stats, token_level_stats, blank_token_level_stats,
    positional_letter_stats, blank_positional_letter_stats,
    letter_freq_rank_stats, script_composition_stats,
)
from pipeline.langcodes import LANGUAGE_NAMES, UNSUPPORTED_LANGUAGES

DEFAULT_WINDOW_SIZES = [100, 500, 1000, 2000, 5000, 10000]
DEFAULT_N_SAMPLES = 30
DEFAULT_MAX_CORPUS_CHARS = 3_000_000
MIN_WORDS_FOR_TOKEN_STATS = 10

BASE_FIELDS_EXCLUDED_FROM_SUMMARY = {
    "language", "language_name", "cipher", "cipher_category", "window_size",
    "sample_id", "seed", "corpus_offset", "label_key_repr", "preserves_word_boundaries",
}


def extract_cipher_symbols(text, cipher_spec, alphabet_set):
    """The "letters" stream to run letter/bigram stats over: for ciphers
    that pass spaces/punctuation through unchanged, drop those passthrough
    characters and keep only actual cipher-output symbols; for ciphers
    whose entire output is a pure symbol stream, use it as-is."""
    if cipher_spec is None or cipher_spec.preserves_word_boundaries:
        if cipher_spec and cipher_spec.category == "homophonic":
            return [c for c in text if PUA_START <= ord(c) < PUA_START + PUA_CAPACITY]
        return [c for c in text if c in alphabet_set]
    return list(text)


def compute_letter_and_relation_stats(letters, universe_size):
    out = {}
    out.update(unigram_stats(letters, universe_size=universe_size, prefix="letter"))
    out.update(bigram_stats(letters, prefix="letter_bigram"))
    out.update(repeat_spacing_stats(letters, n=3, prefix="letter_trigram_repeat"))
    out.update(letter_freq_rank_stats(letters, k=20, prefix="letter"))
    out.update(script_composition_stats(letters, prefix="letter"))
    return out


def compute_word_and_morpheme_stats(text_with_boundaries):
    words = tokenize_words(text_with_boundaries)
    if len(words) < MIN_WORDS_FOR_TOKEN_STATS:
        return (blank_token_level_stats("word"), blank_token_level_stats("morpheme"),
                blank_positional_letter_stats("letter"), False)
    word_stats = token_level_stats(words, "word")
    merges = train_bpe(text_with_boundaries)
    morphemes = segment_text(text_with_boundaries, merges)
    morph_stats = token_level_stats(morphemes, "morpheme")
    pos_stats = positional_letter_stats(words, "letter")
    return word_stats, morph_stats, pos_stats, True


def build_row(lang, lang_name, cipher_spec, window_size, sample_id, corpus_text,
              alphabet, alphabet_set, alphabet_size, word_segmented_flag):
    seed = f"{lang}|{cipher_spec.id if cipher_spec else 'plaintext'}|{window_size}|{sample_id}"
    rng = random.Random(seed)
    start = rng.randrange(0, len(corpus_text) - window_size + 1)
    plain_sample = corpus_text[start:start + window_size]

    if cipher_spec is None:
        ciphertext, key_repr, category, preserves = plain_sample, "", "plaintext", True
    else:
        ciphertext, key_repr = cipher_spec.fn(plain_sample, alphabet, rng, corpus_text=corpus_text)
        category, preserves = cipher_spec.category, cipher_spec.preserves_word_boundaries

    if cipher_spec and cipher_spec.id == "adfgvx_style":
        universe = 6
    elif cipher_spec and cipher_spec.category == "homophonic":
        universe = homophonic_symbol_budget(alphabet_size)
    else:
        universe = alphabet_size
    row = {
        "language": lang,
        "language_name": lang_name,
        "cipher": cipher_spec.id if cipher_spec else "plaintext",
        "cipher_category": category,
        "window_size": window_size,
        "sample_id": sample_id,
        "seed": seed,
        "corpus_offset": start,
        "label_key_repr": key_repr,
        "alphabet_size_language": alphabet_size,
        "letter_universe_size": universe,
        "preserves_word_boundaries": preserves,
    }
    letters = extract_cipher_symbols(ciphertext, cipher_spec, alphabet_set)
    row.update(compute_letter_and_relation_stats(letters, universe))

    if preserves and word_segmented_flag:
        word_stats, morph_stats, pos_stats, applicable = compute_word_and_morpheme_stats(ciphertext)
    else:
        word_stats, morph_stats, pos_stats, applicable = (
            blank_token_level_stats("word"), blank_token_level_stats("morpheme"),
            blank_positional_letter_stats("letter"), False,
        )
    row["word_level_applicable"] = applicable
    row.update(word_stats)
    row["morpheme_level_applicable"] = applicable
    row.update(morph_stats)
    row.update(pos_stats)
    return row


def summarize(rows, group_key="window_size"):
    """Long/tidy aggregate: one row per (window_size, statistic)."""
    by_window = {}
    for row in rows:
        by_window.setdefault(row[group_key], []).append(row)

    summary_rows = []
    stat_keys = [k for k in rows[0].keys() if k not in BASE_FIELDS_EXCLUDED_FROM_SUMMARY]
    for window_size, window_rows in sorted(by_window.items()):
        for key in stat_keys:
            values = []
            for r in window_rows:
                v = r[key]
                if v is None:
                    continue
                if isinstance(v, bool):
                    values.append(1.0 if v else 0.0)
                elif isinstance(v, (int, float)):
                    values.append(float(v))
            n = len(values)
            if n == 0:
                summary_rows.append({
                    "language": window_rows[0]["language"], "cipher": window_rows[0]["cipher"],
                    "window_size": window_size, "statistic": key,
                    "min": None, "max": None, "mean": None, "median": None, "std": None,
                    "n": 0, "n_total_samples": len(window_rows),
                })
                continue
            summary_rows.append({
                "language": window_rows[0]["language"], "cipher": window_rows[0]["cipher"],
                "window_size": window_size, "statistic": key,
                "min": min(values), "max": max(values),
                "mean": pystats.mean(values), "median": pystats.median(values),
                "std": pystats.pstdev(values) if n > 1 else 0.0,
                "n": n, "n_total_samples": len(window_rows),
            })
    return summary_rows


def write_csv(path, rows):
    if not rows:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--languages", default="all",
                    help="Comma-separated language codes, or 'all' (default) for every "
                         "language with enough usable text.")
    p.add_argument("--window-sizes", default=",".join(str(w) for w in DEFAULT_WINDOW_SIZES))
    p.add_argument("--n-samples", type=int, default=DEFAULT_N_SAMPLES)
    p.add_argument("--max-corpus-chars", type=int, default=DEFAULT_MAX_CORPUS_CHARS)
    p.add_argument("--limit-ciphers", default="",
                    help="Comma-separated cipher ids to restrict to (default: all).")
    p.add_argument("--dictionaries-root", default="dictionaries")
    p.add_argument("--output-dir", default="output")
    p.add_argument("--force", action="store_true", help="Rebuild caches and overwrite existing CSVs.")
    return p.parse_args()


def main():
    args = parse_args()
    window_sizes = sorted(int(w) for w in args.window_sizes.split(",") if w)
    n_samples = args.n_samples
    output_dir = args.output_dir
    csv_dir = os.path.join(output_dir, "csv")
    manifest_csv = os.path.join(output_dir, "corpus_manifest.csv")

    cipher_ids = set(args.limit_ciphers.split(",")) if args.limit_ciphers else None
    ciphers_to_run = [c for c in CIPHERS if not cipher_ids or c.id in cipher_ids]

    print(f"[1/4] Scanning {args.dictionaries_root} ...", file=sys.stderr)
    entries = build_manifest(args.dictionaries_root, manifest_csv)
    usable = sum(1 for e in entries if e.usable)
    print(f"      {len(entries)} files found, {usable} usable, manifest -> {manifest_csv}", file=sys.stderr)

    grouped = group_usable_by_language(entries)
    grouped.pop("unknown", None)
    for lang in UNSUPPORTED_LANGUAGES:
        grouped.pop(lang, None)

    # Languages fetched via training/fetch_leipzig_corpora.py already have a
    # built output/corpora/<lang>.txt + output/alphabets/<lang>.json cache
    # and no raw files under dictionaries/ at all (that script talks straight
    # to the Leipzig download API, bypassing the manifest scan entirely) --
    # get_or_build_corpus() returns the cache immediately without touching
    # `paths` when it exists, so an empty list here is enough to make sure
    # the main loop below still visits them.
    corpora_dir = os.path.join(args.output_dir, "corpora")
    if os.path.isdir(corpora_dir):
        cached_langs = {f[:-4] for f in os.listdir(corpora_dir) if f.endswith(".txt")}
        for lang in cached_langs - set(grouped) - UNSUPPORTED_LANGUAGES:
            grouped[lang] = []

    if args.languages != "all":
        wanted = set(args.languages.split(","))
        grouped = {lang: paths for lang, paths in grouped.items() if lang in wanted}

    run_index_rows = []
    skip_log = []

    for i, (lang, paths) in enumerate(sorted(grouped.items()), 1):
        lang_name = LANGUAGE_NAMES.get(lang, lang)
        t0 = time.time()
        corpus_text, alphabet, freqs = get_or_build_corpus(
            lang, paths, output_dir, args.max_corpus_chars, force=args.force)
        alphabet_set = set(alphabet)
        alphabet_size = len(alphabet)

        if len(corpus_text) < MIN_USABLE_CORPUS_CHARS or alphabet_size < 2:
            skip_log.append((lang, "insufficient corpus/alphabet",
                              len(corpus_text), alphabet_size))
            print(f"  [{i}/{len(grouped)}] {lang} ({lang_name}): SKIPPED "
                  f"(chars={len(corpus_text)}, alphabet={alphabet_size})", file=sys.stderr)
            continue

        word_segmented_flag = is_word_segmented(lang, corpus_text)
        feasible_windows = [w for w in window_sizes if len(corpus_text) > w]

        print(f"  [{i}/{len(grouped)}] {lang} ({lang_name}): chars={len(corpus_text)} "
              f"alphabet={alphabet_size} word_segmented={word_segmented_flag} "
              f"windows={feasible_windows}", file=sys.stderr)

        cipher_specs = [None] + [c for c in ciphers_to_run if c.applicable(alphabet_size)]

        for cipher_spec in cipher_specs:
            cid = cipher_spec.id if cipher_spec else "plaintext"
            samples_path = os.path.join(csv_dir, f"{lang}__{cid}__samples.csv")
            summary_path = os.path.join(csv_dir, f"{lang}__{cid}__windowsummary.csv")

            if not args.force and os.path.exists(samples_path) and os.path.exists(summary_path):
                run_index_rows.append({
                    "language": lang, "language_name": lang_name, "cipher": cid,
                    "status": "cached", "n_rows": "", "windows": ",".join(str(w) for w in feasible_windows),
                })
                continue

            rows = []
            for w in feasible_windows:
                for sample_id in range(n_samples):
                    rows.append(build_row(lang, lang_name, cipher_spec, w, sample_id,
                                           corpus_text, alphabet, alphabet_set, alphabet_size,
                                           word_segmented_flag))
            if not rows:
                run_index_rows.append({
                    "language": lang, "language_name": lang_name, "cipher": cid,
                    "status": "no_feasible_windows", "n_rows": 0, "windows": "",
                })
                continue

            write_csv(samples_path, rows)
            write_csv(summary_path, summarize(rows))
            run_index_rows.append({
                "language": lang, "language_name": lang_name, "cipher": cid,
                "status": "generated", "n_rows": len(rows),
                "windows": ",".join(str(w) for w in feasible_windows),
            })

        print(f"      done in {time.time() - t0:.1f}s", file=sys.stderr)

    write_csv(os.path.join(output_dir, "run_index.csv"), run_index_rows)
    write_readme(output_dir, ciphers_to_run, window_sizes, n_samples, skip_log)
    print(f"[4/4] Wrote {len(run_index_rows)} language/cipher entries -> "
          f"{os.path.join(output_dir, 'run_index.csv')}", file=sys.stderr)


def write_readme(output_dir, ciphers, window_sizes, n_samples, skip_log):
    lines = []
    lines.append("# Cipher statistics dataset\n")
    lines.append(
        "Generated by `run_pipeline.py`. Each `output/csv/<lang>__<cipher>__samples.csv` holds "
        "one row per random text-window sample; `..._windowsummary.csv` holds the aggregated "
        "min/max/mean/median/std of every statistic, grouped by window size (the "
        "\"range of variance across window sizes\" view, including character-set-size range).\n"
    )
    lines.append(f"Window sizes: {window_sizes}. Samples per (language, cipher, window): {n_samples}.\n")
    lines.append("## Scope decisions\n")
    lines.append("- Ciphers are classical/historical only (see `pipeline/ciphers.py`): "
                  "substitution/polyalphabetic (Caesar, Atbash, monoalphabetic substitution, "
                  "Vigenere, Beaufort, Autokey, running-key, a generalized Porta-style cipher), "
                  "homophonic (proportional-allocation and flat-allocation variants -- see the "
                  "note below), digraphic/grid (Playfair, two-square, four-square, Bifid, Trifid, "
                  "Hill 2x2, an ADFGVX-style fractionated+transposed cipher), and transposition "
                  "(rail fence, columnar, route/spiral). Modern block ciphers are out of scope: "
                  "their output is close to uniformly random, which isn't a meaningful "
                  "cryptanalysis statistics target.\n")
    lines.append("- **Homophonic substitution** (`homophonic_substitution` / "
                  "`homophonic_flat_substitution`) maps each plaintext letter to a pool of "
                  "ciphertext symbols (single Private-Use-Area characters), redrawn per "
                  "occurrence, sized to `alphabet_size + min(300, 2*alphabet_size)` total "
                  "symbols (see `letter_universe_size`). This is the one cipher family whose "
                  "output alphabet is LARGER than the input alphabet, and it's specifically "
                  "designed to flatten letter frequency -- expect its `letter_ic_raw` well below "
                  "every other substitution/polyalphabetic cipher, including Vigenere. The "
                  "`_proportional` variant sizes each letter's homophone pool to its language "
                  "frequency (the textbook design); `_flat` gives every letter about the same "
                  "pool size regardless of frequency, which flattens the distribution far less "
                  "and behaves differently under `letter_chao1_estimate` (see below) -- the pair "
                  "exists specifically so a downstream model can be tested on whether it "
                  "distinguishes allocation strategy, not just \"is this homophonic.\" Standard "
                  "unigram-frequency-based language ID does not transparently transfer to "
                  "homophonic ciphertext (that's the point of the cipher); word-length "
                  "distribution and the word-initial/word-final letter stats below are the "
                  "features that still carry language signal through it.\n")
    lines.append("- Grid ciphers (Playfair/two-square/four-square/Bifid/Trifid/Hill/ADFGVX) only "
                  "run for languages whose derived alphabet is small enough to grid sensibly "
                  "(<=100 symbols; ADFGVX-style <=36). Large-inventory scripts (e.g. Chinese) "
                  "skip these; see `run_index.csv` for what actually ran per language.\n")
    lines.append("- Substitution/polyalphabetic ciphers pass non-alphabet characters (spaces, "
                  "punctuation) through unchanged, so word boundaries survive in their output. "
                  "Digraphic and transposition ciphers operate on the letters-only stream, so "
                  "word/morpheme-level columns are blank for their rows (`preserves_word_boundaries`, "
                  "`word_level_applicable`, `morpheme_level_applicable` record this explicitly -- "
                  "its absence is itself an ML signal for \"this is a transposition/digraphic "
                  "cipher\").\n")
    lines.append("- \"Morpheme\" columns are a byte-pair-encoding (BPE) proxy, trained fresh "
                  "on each individual sample's own word list (not a shared per-language model) "
                  "so the statistic is derivable from ciphertext alone -- there is no true "
                  "morphological analyzer used. Skipped (blank) when a sample has fewer than "
                  f"{MIN_WORDS_FOR_TOKEN_STATS} words.\n")
    lines.append("- Word/morpheme-level statistics are skipped entirely for languages whose "
                  "script isn't conventionally whitespace-word-segmented (Chinese, Japanese, "
                  "Thai, Khmer, Burmese, Dzongkha, or any language whose observed average "
                  "whitespace-token length looks unsegmented) -- see `pipeline/tokenize.py`. "
                  "Letter and letter-bigram statistics still cover these languages fully.\n")
    lines.append("- Text is NFC-normalized and lowercased before any cipher/statistics step.\n")
    lines.append("- `label_key_repr` is the ground-truth cipher key for that sample -- it's a "
                  "label for evaluating key-recovery models, not a feature; don't feed it to a "
                  "language- or mapping-identification model as input.\n")
    lines.append("## Column glossary\n")
    lines.append(
        "- `letter_universe_size`: the size of the symbol space letter-level stats are actually "
        "normalized against for THIS cipher's output -- equal to `alphabet_size_language` for "
        "most ciphers, but 6 for `adfgvx_style` and the (larger) homophonic codespace size for "
        "the homophonic ciphers. `window_size / letter_universe_size` is a more meaningful "
        "\"how much data per symbol\" covariate than raw window size alone, particularly for "
        "homophonic ciphertext, where the effective number of symbols being estimated can be "
        "3-4x the plaintext alphabet size.\n"
        "- `letter_*`: unigram stats over alphabet-member characters only (spaces/punctuation "
        "excluded). `letter_distinct_count` is the character-set size the window actually used; "
        "look at the corresponding `windowsummary.csv` row for its min/max/mean range per window "
        "size. `letter_chao1_estimate` is a species-richness estimate of the TRUE symbol "
        "inventory size from the observed sample alone (Chao1: distinct-count plus a correction "
        "term from how many symbols were seen exactly once/twice) -- useful wherever the "
        "observed distinct count likely undercounts the true alphabet, which is exactly the "
        "homophonic case, but computed for every cipher/level for consistency. `letter_ic_raw`/"
        "`letter_ic_normalized` (normalized = raw * `letter_universe_size`, comparable across "
        "languages/scripts and across ciphers whose output alphabet size differs from the input "
        "alphabet), `letter_entropy`, `letter_redundancy`, `letter_chi2_uniform`.\n"
        "- `letter_bigram_*`: adjacent-letter-pair stats (the letter-to-letter relational measure).\n"
        "- `letter_trigram_repeat_*`: Kasiski-style repeated-trigram spacing (`mean_spacing`, "
        "`gcd_spacing`) -- classical polyalphabetic key-length clue.\n"
        "- `letter_word_initial_*` / `letter_word_final_*`: IC/entropy of the word-initial and "
        "word-final letter distributions specifically (not all letter positions pooled together). "
        "This positional structure is one of the few things that survives ciphers which redraw a "
        "fresh symbol per occurrence (homophonic substitution) as long as word boundaries "
        "survive -- compare a sample's values here against the per-language reference tables in "
        "`output/language_profiles/<lang>.json` (built by `build_language_profiles.py`) rather "
        "than raw unigram frequency. Blank wherever word-level stats aren't applicable.\n"
        "- `word_*` / `word_bigram_*` and `morpheme_*` / `morpheme_bigram_*`: same shape as the "
        "letter-level stats but over word or BPE-morpheme tokens, plus `*_type_token_ratio` and "
        "`*_mean_length`/`*_std_length`. `word_type_token_ratio` close to 1.0 (few or no repeated "
        "word-forms) is itself a signal specific to homophonic substitution: because every "
        "occurrence of a word redraws fresh symbols, the same plaintext word essentially never "
        "produces the same ciphertext form twice, unlike monoalphabetic substitution where it "
        "always does.\n"
        "- Per-symbol raw frequency/rank (e.g. \"this is probably E because it's the most common "
        "symbol\") is NOT a reliable feature for homophonic ciphertext and isn't computed as a "
        "standalone column here -- a rare letter with one homophone can outrank an individual "
        "homophone of a common letter. It's a legitimate input to Chao1/IC/entropy in aggregate, "
        "just not to a per-symbol identity ranking.\n"
    )
    lines.append("## Per-language reference profiles\n")
    lines.append(
        "`build_language_profiles.py` (run separately from `run_pipeline.py`) writes "
        "`output/language_profiles/<lang>.json` from each language's cached corpus: "
        "word-initial and word-final letter frequency tables, a word-length distribution, and "
        "the top 5,000 words by frequency. These are corpus-level ground truth (not per-sample), "
        "meant as (a) the reference to compare `letter_word_initial_*`/`letter_word_final_*` "
        "against, and (b) the input a plausible-plaintext/crossword-style recovery stage would "
        "need -- a frequency-ranked common-word list avoids the ambiguity a raw dictionary full "
        "of archaic/rare entries introduces. Skipped for languages that aren't "
        "whitespace-word-segmented or have too little text.\n"
    )
    if skip_log:
        lines.append("## Languages skipped (insufficient usable text/alphabet)\n")
        for lang, reason, chars, alpha in skip_log:
            lines.append(f"- `{lang}`: {reason} (chars={chars}, alphabet_size={alpha})\n")

    os.makedirs(output_dir, exist_ok=True)
    with open(os.path.join(output_dir, "README.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    main()
